#include "DatosPredeterminados.h"
using namespace std;
// Registra cursos obligatorios y electivos usando codigos faciles de reconocer
vector<Curso> DatosPredeterminados::obtenerCursos() {
    return {
        {"LCOM1", "LENGUAJE Y COMUNICACION I", "General", 4},
        {"LCOM2", "LENGUAJE Y COMUNICACION II", "General", 3},
        {"PSICO", "PROCESOS PSICOLOGICOS", "General", 3},
        {"ETICA", "ETICA CIUDADANA", "General", 2},
        {"METINV", "METODOLOGIAS DE INVESTIGACION", "General", 3},
        {"COMINT", "INTRODUCCION AL COMERCIO INTERNACIONAL", "General", 3},
        {"ECON", "FUNDAMENTOS DE ECONOMIA", "General", 3},
        {"FILO", "FILOSOFIA APLICADA", "General", 3},
        {"GERENC", "DESARROLLO DE COMPETENCIAS GERENCIALES", "General", 3},
        {"INGING", "INTRODUCCION A LA INGENIERIA", "General_Ingenieria", 3},
        {"FISSIS", "FISICA PARA SISTEMAS", "General_Ingenieria", 4},
        {"COSTOP", "COSTEO DE OPERACIONES", "General_Ingenieria", 3},
        {"SSOB", "SEGURIDAD SALUD OCUPACIONAL Y BIENESTAR ORGANIZACIONAL", "General_Ingenieria", 3},
        {"PRECAL", "PRECALCULO", "Matematica", 5},
        {"ALGEB", "ALGEBRA LINEAL", "Matematica", 3},
        {"CALC1", "CALCULO I", "Matematica", 5},
        {"CALC2", "CALCULO II", "Matematica", 5},
        {"CALC3", "CALCULO III", "Matematica", 3},
        {"ESTPROB", "ESTADISTICA Y PROBABILIDAD", "Matematica", 4},
        {"ESTAPL", "ESTADISTICA APLICADA", "Matematica", 4},
        {"IO1", "INVESTIGACION DE OPERACIONES I", "Matematica", 4},
        {"SIM", "SIMULACION", "Matematica", 3},
        {"PROPINV", "PROPUESTA DE INVESTIGACION", "General_Sistemas", 3},
        {"SEMINV1", "SEMINARIO DE INVESTIGACION I", "General_Sistemas", 4},
        {"SEMINV2", "SEMINARIO DE INVESTIGACION II", "General_Sistemas", 4},
        {"GFIN", "GESTION FINANCIERA", "General_Sistemas", 3},
        {"AUDCTRL", "AUDITORIA Y CONTROL DE SISTEMAS", "General_Sistemas", 3},
        {"GPROY", "GESTION DE PROYECTOS", "General_Sistemas", 3},
        {"PROINT", "PROYECTO INTEGRADOR DE SISTEMAS", "General_Sistemas", 4},
        {"SISORG", "SISTEMAS ORGANIZACIONALES", "Procesos", 2},
        {"MODINTSIS", "MODELACION E INTEGRACION DE SISTEMAS", "Procesos", 3},
        {"INGPROCNEG", "INGENIERIA DE PROCESOS DE NEGOCIO", "Procesos", 3},
        {"GESTOP", "GESTION DE OPERACIONES", "Procesos", 3},
        {"ERP", "SISTEMAS ERP", "Procesos", 3},
        {"SIE", "SISTEMAS DE INTELIGENCIA EMPRESARIAL", "Procesos", 4},
        {"PLANEST", "PLANEAMIENTO ESTRATEGICO", "Procesos", 3},
        {"INNDIG", "INNOVACION DIGITAL", "Procesos", 3},
        {"ARQEMP", "ARQUITECTURA EMPRESARIAL", "Procesos", 3},
        {"GBD", "GESTION DE BASE DE DATOS", "Datos", 3},
        {"INGCON", "INGENIERIA DEL CONOCIMIENTO", "Datos", 3},
        {"BIGDATA", "ANALITICA CON BIG DATA", "Datos", 3},
        {"ANNEG", "ANALITICA DE NEGOCIOS", "Datos", 3},
        {"IAAPL", "INTELIGENCIA ARTIFICIAL APLICADA", "IA", 3},
        {"ML", "APRENDIZAJE DE MAQUINA", "IA", 4},
        {"DL", "DEEP LEARNING", "IA", 3},
        {"INTPROG", "INTRODUCCION A LA PROGRAMACION", "Software", 4},
        {"ESDIS", "ESTRUCTURAS DISCRETAS DE COMPUTACION", "Software", 4},
        {"POO", "PROGRAMACION ORIENTADA A OBJETOS", "Software", 4},
        {"EDD1", "ESTRUCTURAS DE DATOS I", "Software", 4},
        {"EDD2", "ESTRUCTURAS DE DATOS II", "Software", 4},
        {"MODBD", "MODELAMIENTO DE BASE DE DATOS", "Software", 4},
        {"PROGWEB", "PROGRAMACION WEB", "Software", 3},
        {"ISW1", "INGENIERIA DE SOFTWARE I", "Software", 4},
        {"ISW2", "INGENIERIA DE SOFTWARE II", "Software", 4},
        {"PARPROG", "PARADIGMAS DE PROGRAMACION", "Software", 3},
        {"ADA", "ANALISIS Y DISENO DE ALGORITMOS", "Software", 3},
        {"PROGMOV", "PROGRAMACION MOVIL", "Software", 3},
        {"PROYDS", "PROYECTO DE DESARROLLO DE SOFTWARE", "Software", 3},
        {"ARQSOFT", "ARQUITECTURA DE SOFTWARE", "Software", 3},
        {"IHC", "INTERACCION HUMANO COMPUTADORA", "Software", 3},
        {"STORY", "STORYTELLING", "Software", 3},
        {"DISVID", "DISENO DE VIDEOJUEGOS", "Software", 5},
        {"NARGRAF", "NARRATIVA GRAFICA", "Software", 3},
        {"PROYVID", "PROYECTO DE VIDEOJUEGOS", "Software", 3},
        {"ARQCOMP", "ARQUITECTURA DE COMPUTADORAS", "TI", 4},
        {"SISOP", "SISTEMAS OPERATIVOS", "TI", 4},
        {"REDES", "REDES DE COMPUTADORAS", "TI", 4},
        {"CIBER", "CIBERSEGURIDAD", "TI", 4},
        {"SEGSIS", "SEGURIDAD DE SISTEMAS", "TI", 4},
        {"IOT", "INTERNET DE LAS COSAS", "TI", 3},
        {"REDAV", "REDES AVANZADAS", "TI", 3},
        {"CIBERAV", "TOPICOS AVANZADOS EN CIBERSEGURIDAD", "TI", 3},
        {"SISDIST", "SISTEMAS DISTRIBUIDOS", "TI", 3},
        {"CLOUD", "COMPUTACION EN LA NUBE", "TI", 3},
        {"GSDIG", "GESTION DE SERVICIOS DIGITALES", "TI", 4},
        {"ARQTI", "ARQUITECTURA DE TECNOLOGIAS DE LA INFORMACION", "TI", 3},
        {"DEVOPS", "DEVOPS", "TI", 3}
    };
}

// Registra prerrequisitos usando los mismos codigos reconocibles de cursos.csv
vector<Prerrequisito> DatosPredeterminados::obtenerPrerrequisitos() {
    return {
        {"LCOM2", "LCOM1"},
        {"ALGEB", "PRECAL"},
        {"CALC1", "PRECAL"},
        {"CALC2", "CALC1"},
        {"CALC3", "CALC2"},
        {"ESTPROB", "CALC1"},
        {"ESTAPL", "ESTPROB"},
        {"IO1", "CALC3"},
        {"SISORG", "ECON"},
        {"MODINTSIS", "IAAPL"},
        {"ARQCOMP", "FISSIS"},
        {"COSTOP", "SISORG"},
        {"POO", "ESDIS"},
        {"POO", "INTPROG"},
        {"SISOP", "ARQCOMP"},
        {"GERENC", "SISORG"},
        {"EDD1", "POO"},
        {"MODBD", "POO"},
        {"INGPROCNEG", "IO1"},
        {"REDES", "SISOP"},
        {"SIM", "MODINTSIS"},
        {"EDD2", "EDD1"},
        {"PROGWEB", "EDD1"},
        {"GFIN", "COSTOP"},
        {"SIE", "MODBD"},
        {"GESTOP", "INGPROCNEG"},
        {"ISW1", "MODBD"},
        {"ML", "ESTAPL"},
        {"CIBER", "REDES"},
        {"PROPINV", "SIM"},
        {"ERP", "GESTOP"},
        {"AUDCTRL", "GFIN"},
        {"ISW2", "ISW1"},
        {"GPROY", "AUDCTRL"},
        {"SEMINV1", "PROPINV"},
        {"SEGSIS", "CIBER"},
        {"SEMINV2", "SEMINV1"},
        {"PROINT", "GPROY"},
        {"ADA", "EDD2"},
        {"REDAV", "REDES"},
        {"DL", "ML"},
        {"PROGMOV", "PROGWEB"},
        {"CIBERAV", "CIBER"},
        {"BIGDATA", "SIE"},
        {"PROYDS", "ISW2"},
        {"ARQEMP", "PLANEST"},
        {"DISVID", "STORY"},
        {"NARGRAF", "STORY"}
    };
}

// Crea notas de prueba con cursos aprobados y desaprobados para validar las consultas
vector<RegistroHistorial> DatosPredeterminados::obtenerHistorial() {
    return {
        {"estudiante1", "LCOM1", 15},
        {"estudiante1", "PRECAL", 14},
        {"estudiante1", "INTPROG", 16},
        {"estudiante1", "ESDIS", 12},
        {"estudiante1", "POO", 10},
        {"estudiante1", "IAAPL", 13},
        {"estudiante2", "LCOM1", 11},
        {"estudiante2", "PRECAL", 9},
        {"estudiante2", "INTPROG", 12},
        {"estudiante2", "ESDIS", 8},
        {"estudiante2", "ECON", 14},
        {"estudiante2", "SISORG", 16}
    };
}

// Define intereses iniciales usando las mismas areas usadas en cursos.csv
vector<Interes> DatosPredeterminados::obtenerIntereses() {
    return {
        {"estudiante1", "Software"},
        {"estudiante1", "IA"},
        {"estudiante1", "Datos"},
        {"estudiante2", "Procesos"},
        {"estudiante2", "TI"},
        {"estudiante2", "General_Sistemas"}
    };
}
